name: test

on:
  push:
    branches:
      - main
  pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: v1.1.0

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes | grep -v -E "(CaliburEntryUtils|Mock.*|BaseAuthorization)"
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test

      - name: Run Forge integration tests
        run: |
          forge test -vvv
        id: integ-test
        env:
          FOUNDRY_PROFILE: fork
          FORK_URL: '${{ secrets.FORK_URL }}'


      - name: Run Forge fmt check
        run: |
          forge fmt --check
        id: fmt
